### ISSUE TITLE
Calculation of FPS

### ISSUE THREAD

**Issue by devshree07** [TeCSAR-UNCC/EfficientHRNet#7]
I was reproducing the results of EfficientHRNet and wanted to benchmark the FPS increase in comparison with HRNet. I am not getting the exact numbers (i.e 3.4x) as mentioned in the paper. I think I am doing it in the wrong way. Can you throw some light on the same?

Here is my approach to calculate FPS:
In the **validate function** of lib/core/function.py
I started the time above the line: outputs = model(input) and the end time was calculated before the start of the flip test.

Am I doing it right?

**Comment by ghost** [comment]
We measure just the inference time of the network, aka the time it takes to execute the line
outputs = model(input)
as you has assumed. But as stated in our paper, we used TensorRT to inference on the NX Xavier. When we wrote this paper we were first converting the networks to ONNX and then to TRT, but we've recently switch to going straight from Pytorch to TRT and have had great results, so we would recommend that path.

We also averaged over 10,000 images using a batch size of one, giving a warmup and cooldown of 100 images at the start and end, and ran the test five times to ensure our results were consistent.

What device are you inferencing on? FPS is highly dependent on the device you are running, so if it is different than the NX Xavier that we used, your results will likely also be different. I expect if you're using a more powerful device, such as a Titan V or similar desktop GPU, you will find HigherHRNet will not be significantly slower than EfficientHRNet, with or without TRT inference.
